server_address: "127.0.0.1"
server_port: "50051"
tasks_file: "${PROGRAMDATA}/sPlanner/tasks.yaml"
log_folder: "${PROGRAMDATA}/sPlanner/logs"
log_limit: 10
ssl:
    crt: ""
    key: ""
    ca: ""
    client_cert: false
apps:
