server_address: "127.0.0.1"
server_port: "50051"
tasks_file: tasks.yaml
log_folder: ./logs
log_limit: 5
ssl:
    crt: ""
    key: ./certs/server/server.key
    ca: ./certs/ca/ca.crt
    client_cert: true
apps:
    app1: testApp1.exe
